"""chat turn persistence: conversation history and message tool_calls

Revision ID: 3cc5462f2ff9
Revises: d0911613091d
Create Date: 2026-08-05 22:35:10.866605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc5462f2ff9'
down_revision: Union[str, Sequence[str], None] = 'd0911613091d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('history_json', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('tool_calls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_calls')
    op.drop_column('conversations', 'history_json')
    # ### end Alembic commands ###
