"""initial schema

Revision ID: d0911613091d
Revises: 
Create Date: 2026-08-05 17:02:58.651185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import app.models.types


# revision identifiers, used by Alembic.
revision: str = 'd0911613091d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', app.models.types.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', app.models.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('listing_type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_unit', sa.String(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('area_sqm', sa.Float(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('listed_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_agent_id'), 'properties', ['agent_id'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_listed_date'), 'properties', ['listed_date'], unique=False)
    op.create_index(op.f('ix_properties_listing_type'), 'properties', ['listing_type'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_table('availability_slots',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('slot_time', app.models.types.UtcDateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_slots_agent_id'), 'availability_slots', ['agent_id'], unique=False)
    op.create_index(op.f('ix_availability_slots_property_id'), 'availability_slots', ['property_id'], unique=False)
    op.create_index(op.f('ix_availability_slots_slot_time'), 'availability_slots', ['slot_time'], unique=False)
    op.create_index(op.f('ix_availability_slots_status'), 'availability_slots', ['status'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('escalated_by_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('conversation_summary', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=True),
    sa.Column('assigned_agent_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', app.models.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['escalated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_assigned_agent_id'), 'escalations', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_escalations_category'), 'escalations', ['category'], unique=False)
    op.create_index(op.f('ix_escalations_conversation_id'), 'escalations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_escalations_created_at'), 'escalations', ['created_at'], unique=False)
    op.create_index(op.f('ix_escalations_escalated_by_id'), 'escalations', ['escalated_by_id'], unique=False)
    op.create_index(op.f('ix_escalations_property_id'), 'escalations', ['property_id'], unique=False)
    op.create_index(op.f('ix_escalations_status'), 'escalations', ['status'], unique=False)
    op.create_index(op.f('ix_escalations_urgency'), 'escalations', ['urgency'], unique=False)
    op.create_table('messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('availability_slot_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('slot_time', app.models.types.UtcDateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rescheduled_count', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['availability_slot_id'], ['availability_slots.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_agent_id'), 'bookings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_bookings_availability_slot_id'), 'bookings', ['availability_slot_id'], unique=False)
    op.create_index(op.f('ix_bookings_client_id'), 'bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_property_id'), 'bookings', ['property_id'], unique=False)
    op.create_index(op.f('ix_bookings_slot_time'), 'bookings', ['slot_time'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_slot_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_property_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_client_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_availability_slot_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_agent_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_escalations_urgency'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_status'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_property_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_escalated_by_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_created_at'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_conversation_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_category'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_assigned_agent_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_availability_slots_status'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_slot_time'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_property_id'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_agent_id'), table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_listing_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_listed_date'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_agent_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
