"""``/api/v1/properties`` — the dashboard's property surface.

Visibility on the read path comes from ``app/property/queries.py``'s shared scoped
query, the same builder ``SearchProperty`` and ``escalate_to_human``'s assignment lookup
use, so the chat and dashboard surfaces cannot disagree about what a user may see.
Filters compose *onto* that scope, so ``?status=draft`` from a client narrows an
already-active-only set to nothing rather than revealing drafts.

Writes resolve through the narrower ``editable_property_query``: an agent reads every
active listing but owns only their own. A listing outside that set answers ``404``, not
``403`` — ``403`` stays reserved for a role that may not touch the endpoint at all.
"""

import logging
from datetime import date
from typing import Annotated

from fastapi import APIRouter, Depends, Query
from sqlmodel import Session, col

from app.api.deps import CurrentUser, DbSession, enforce_csrf, require_role
from app.api.pagination import Page, PageParamsDep, paginate
from app.core.exceptions import (
    InvalidAgentIdError,
    InvalidPriceRangeError,
    PropertyNotFoundError,
)
from app.models import (
    ListingType,
    Property,
    PropertyStatus,
    PropertyType,
    User,
)
from app.property.queries import (
    PropertyFilters,
    apply_property_filters,
    find_editable_property,
    scoped_property_query,
)
from app.schemas.property import PropertyDetail, PropertySummary, PropertyWriteRequest

logger = logging.getLogger(__name__)

# enforce_csrf at router level rather than per-route: it is a no-op for GET/HEAD/OPTIONS
# and for Bearer callers (app/api/deps.py), so declaring it once removes the possibility
# of a future write endpoint forgetting it.
router = APIRouter(
    prefix="/properties", tags=["properties"], dependencies=[Depends(enforce_csrf)]
)

# Deactivation target: `draft` is the only non-public, non-terminal status — `sold`
# would assert a sale that did not happen.
DEACTIVATED_STATUS: PropertyStatus = "draft"

PROPERTY_SORT_COLUMNS = {
    "listed_date": col(Property.listed_date),
    "price": col(Property.price),
    "title": col(Property.title),
    "city": col(Property.city),
}
DEFAULT_PROPERTY_SORT = "-listed_date"

PropertyWriter = Annotated[User, Depends(require_role("admin", "agent"))]


def _owner_for(db: Session, caller: User, requested_agent_id: str | None) -> str | None:
    """An ``agent`` always owns what they write, whatever the body claims.

    Ownership decided by a request field would let an agent park a listing on a
    colleague, and (via the escalation assignment path) attribute escalations to them.

    Only an ``admin`` reaches the lookup below, and the id they supply is checked
    *before* the write: `properties.agent_id` is a foreign key, so an unknown id would
    otherwise fail at the INSERT and surface as a 500 for what is a bad request field.
    The role check is part of the same question — a `client` cannot conduct a viewing,
    and a listing owned by one is unbookable.
    """
    if caller.role == "agent":
        return caller.id
    if requested_agent_id is None:
        return None

    owner = db.get(User, requested_agent_id)
    if owner is None or owner.role not in ("agent", "admin"):
        raise InvalidAgentIdError()
    return owner.id


def _write_values(
    db: Session, payload: PropertyWriteRequest, caller: User
) -> dict[str, object]:
    """The mutable column set, shared by create and the full-replace PUT.

    ``id`` is absent on purpose: it is generated by the model, never supplied.
    """
    return {
        **payload.model_dump(exclude={"agent_id", "listed_date"}),
        "agent_id": _owner_for(db, caller, payload.agent_id),
        "listed_date": payload.listed_date or date.today(),
    }


@router.get("", response_model=Page[PropertySummary])
def list_properties(
    user: CurrentUser,
    db: DbSession,
    params: PageParamsDep,
    q: Annotated[str | None, Query(description="Free text over title, description, address")] = None,
    city: Annotated[list[str] | None, Query(description="Exact city match, repeatable")] = None,
    status: Annotated[list[PropertyStatus] | None, Query(description="Repeatable")] = None,
    property_type: Annotated[list[PropertyType] | None, Query(description="Repeatable")] = None,
    listing_type: Annotated[ListingType | None, Query()] = None,
    agent_id: Annotated[str | None, Query()] = None,
    min_price: Annotated[float | None, Query(ge=0)] = None,
    max_price: Annotated[float | None, Query(ge=0)] = None,
    bedrooms: Annotated[int | None, Query(ge=0, description="Minimum bedrooms")] = None,
) -> Page[PropertySummary]:
    """List the properties this caller may see."""
    if min_price is not None and max_price is not None and min_price > max_price:
        raise InvalidPriceRangeError()

    statement = apply_property_filters(
        scoped_property_query(user),
        PropertyFilters(
            text=q,
            cities=tuple(city or ()),
            statuses=tuple(status or ()),
            property_types=tuple(property_type or ()),
            listing_type=listing_type,
            agent_id=agent_id,
            min_price=min_price,
            max_price=max_price,
            bedrooms=bedrooms,
        ),
    )

    page = paginate(
        db,
        statement,
        params,
        sort_columns=PROPERTY_SORT_COLUMNS,
        default_sort=DEFAULT_PROPERTY_SORT,
        item_factory=PropertySummary.from_property,
    )
    logger.info(
        "properties_listed",
        extra={"user_id": user.id, "role": user.role, "total": page.total},
    )
    return page


@router.post("", response_model=PropertyDetail, status_code=201)
def create_property(
    payload: PropertyWriteRequest, user: PropertyWriter, db: DbSession
) -> PropertyDetail:
    """Create a listing. An ``agent`` always becomes its owner; only an ``admin`` may
    assign one to somebody else."""
    prop = Property(**_write_values(db, payload, user))
    db.add(prop)
    db.commit()
    db.refresh(prop)

    logger.info(
        "property_created",
        extra={"user_id": user.id, "role": user.role, "property_id": prop.id},
    )
    return PropertyDetail.from_property(prop)


@router.put("/{property_id}", response_model=PropertyDetail)
def update_property(
    property_id: str, payload: PropertyWriteRequest, user: PropertyWriter, db: DbSession
) -> PropertyDetail:
    """Replace a listing the caller owns (any listing, for an ``admin``)."""
    prop = find_editable_property(db, user, property_id)
    if prop is None:
        raise PropertyNotFoundError()

    for field, value in _write_values(db, payload, user).items():
        setattr(prop, field, value)
    db.add(prop)
    db.commit()
    db.refresh(prop)

    logger.info(
        "property_updated",
        extra={"user_id": user.id, "role": user.role, "property_id": prop.id},
    )
    return PropertyDetail.from_property(prop)


@router.delete("/{property_id}", response_model=PropertyDetail)
def deactivate_property(
    property_id: str, user: PropertyWriter, db: DbSession
) -> PropertyDetail:
    """Deactivate a listing by returning it to ``draft``.

    Never a row deletion: bookings and escalations reference the property, and removing
    it would orphan them — the same reason users are disabled rather than deleted. The
    updated record comes back so the dashboard can re-render without a second fetch.
    """
    prop = find_editable_property(db, user, property_id)
    if prop is None:
        raise PropertyNotFoundError()

    prop.status = DEACTIVATED_STATUS
    db.add(prop)
    db.commit()
    db.refresh(prop)

    logger.info(
        "property_deactivated",
        extra={"user_id": user.id, "role": user.role, "property_id": prop.id},
    )
    return PropertyDetail.from_property(prop)
