"""Booking domain logic shared by the booking tools and the REST endpoints."""

from app.booking.slots import (
    BookingDomainError,
    BookingNotCancellableError,
    BookingNotFoundError,
    BookingNotReschedulableError,
    BookingSlotConflictError,
    PropertyNotBookableError,
    PropertyNotFoundError,
    RescheduleResult,
    SlotConflictError,
    SlotSuggestion,
    SlotTimeInPastError,
    SlotUnavailableError,
    SlotUnchangedError,
    cancel_booking,
    create_booking,
    find_alternative_slots,
    reschedule_booking,
    resolve_slot,
)

__all__ = [
    "BookingDomainError",
    "BookingNotCancellableError",
    "BookingNotFoundError",
    "BookingNotReschedulableError",
    "BookingSlotConflictError",
    "PropertyNotBookableError",
    "PropertyNotFoundError",
    "RescheduleResult",
    "SlotConflictError",
    "SlotSuggestion",
    "SlotTimeInPastError",
    "SlotUnavailableError",
    "SlotUnchangedError",
    "cancel_booking",
    "create_booking",
    "find_alternative_slots",
    "reschedule_booking",
    "resolve_slot",
]
